spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.25.129/springboot_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
## path: d:/log/tomcat/
#  file: d:/log/tomcat/sell.log
#  level: debug


wxchat:
  mpAppId:
  mpAppSecret: